import argparse
import csv
import re
from collections import Counter

import pandas as pd
from zxcvbn import zxcvbn


DEFAULT_GENERATED = "data/generated_passwords/verified_passwords_v1.csv"
DEFAULT_COMMON = "data/new_dataset/common_passwords.csv"
DEFAULT_OUTPUT = "data/generated_passwords/attackability_results.csv"
DEFAULT_REPORT = "ATTACKABILITY_REPORT.md"

PHRASES = ["summer", "winter", "fall", "spring", "test", "admin", "user"]
SYMBOLS = ["@", "!", "#", "_"]
YEARS = [str(year) for year in range(1990, 2026)]
LEET_REVERSE = str.maketrans({"@": "a", "3": "e", "1": "l", "0": "o", "$": "s"})


def normalize(password):
    return re.sub(r"[^a-z0-9]", "", password.lower().translate(LEET_REVERSE))


def load_common_passwords(path):
    df = pd.read_csv(path)
    passwords = df["password"].dropna().astype(str).tolist()
    normalized = {normalize(password): password for password in passwords}
    return passwords, normalized


def targeted_search_size(common_password_count):
    pattern_count = len(PHRASES) * len(SYMBOLS) * len(YEARS) * 4
    return common_password_count * pattern_count * 2


def is_project_pattern(text):
    for phrase in PHRASES:
        for year in YEARS:
            if text in {f"{phrase}{year}", f"{year}{phrase}"}:
                return True
    return False


def classify_attack(password, common_lookup):
    normalized = normalize(password)

    if normalized in common_lookup:
        return "common_password"

    for split_at in range(1, len(normalized)):
        prefix = normalized[:split_at]
        suffix = normalized[split_at:]

        if prefix in common_lookup and is_project_pattern(suffix):
            return "targeted_rule_match"

        if suffix in common_lookup and is_project_pattern(prefix):
            return "targeted_rule_match"

    for split_at in range(1, len(normalized)):
        prefix = normalized[:split_at]
        suffix = normalized[split_at:]

        if prefix in common_lookup or suffix in common_lookup:
            return "contains_common_password"

    return "not_matched"


def write_report(path, results, generated_count, target_count):
    attack_counts = Counter(row["attack_match_type"] for row in results)
    zxcvbn_counts = Counter(row["zxcvbn_score"] for row in results)
    matched = generated_count - attack_counts["not_matched"]
    matched_rate = matched / generated_count if generated_count else 0

    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("# Attackability Report\n\n")
        f.write("This report evaluates whether generated passwords that score well on zxcvbn are still predictable under a targeted attack model.\n\n")
        f.write("## Inputs\n\n")
        f.write(f"- Generated passwords evaluated: {generated_count}\n")
        f.write(f"- Targeted candidates generated from common passwords and project rules: {target_count}\n")
        f.write("- Targeted rules: common password + season/admin/test/user phrase + year + symbol, in prefix and suffix forms\n\n")
        f.write("## zxcvbn Scores\n\n")
        for score in sorted(zxcvbn_counts):
            f.write(f"- Score {score}: {zxcvbn_counts[score]}\n")
        f.write("\n")
        f.write("## Targeted Attack Matches\n\n")
        for match_type, count in attack_counts.most_common():
            f.write(f"- {match_type}: {count}\n")
        f.write("\n")
        f.write(f"Overall targeted-match rate: {matched_rate:.2%}\n\n")
        f.write("## Interpretation\n\n")
        f.write(
            "The adversarial property is present when a password receives a high zxcvbn score "
            "but is still generated by a compact, attacker-controlled rule set. Those matches "
            "are much cheaper to guess than their meter score suggests because the attacker does "
            "not need to search the full character space.\n"
        )


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate generated passwords against a targeted cracking rule set."
    )
    parser.add_argument("--generated", default=DEFAULT_GENERATED)
    parser.add_argument("--common", default=DEFAULT_COMMON)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--report", default=DEFAULT_REPORT)
    args = parser.parse_args()

    common_passwords, common_lookup = load_common_passwords(args.common)
    target_count = targeted_search_size(len(common_passwords))

    generated_df = pd.read_csv(args.generated)
    rows = []
    for password in generated_df["password"].dropna().astype(str):
        zxcvbn_result = zxcvbn(password)
        rows.append(
            {
                "password": password,
                "zxcvbn_score": zxcvbn_result["score"],
                "zxcvbn_guesses": zxcvbn_result["guesses"],
                "attack_match_type": classify_attack(
                    password, common_lookup
                ),
            }
        )

    with open(args.output, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "password",
                "zxcvbn_score",
                "zxcvbn_guesses",
                "attack_match_type",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    write_report(args.report, rows, len(rows), target_count)
    print(f"Done. Attackability CSV saved to {args.output}")
    print(f"Done. Attackability report saved to {args.report}")


if __name__ == "__main__":
    main()
